# Generated by Django 3.2.7 on 2021-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0002_user_table_make_email_case_insensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
