# Generated by Django 3.1.13 on 2021-08-24 13:29

import uuid

import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KarmaBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", django.contrib.postgres.fields.citext.CICharField(max_length=50)),
                ("slug", models.SlugField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="karmaboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Karmaboard",
                "verbose_name_plural": "Karmaboards",
            },
        ),
        migrations.AddConstraint(
            model_name="karmaboard",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_karmaboard_name_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="karmaboard",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="unique_karmaboard_slug_per_owner"
            ),
        ),
    ]
