# Generated by Django 3.1.13 on 2021-08-26 16:24

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0002_karma_table_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="karmaboard",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=30),
        ),
    ]
