# Generated by Django 3.2.6 on 2021-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0003_karmaboard_table_make_name_max_30_chars"),
    ]

    operations = [
        migrations.AddField(
            model_name="karmaboard",
            name="value_step",
            field=models.CharField(
                choices=[
                    ("BY_1", "By 1"),
                    ("BY_5", "By 5"),
                    ("BY_10", "By 10"),
                    ("FIBONACCI", "Fibonacci"),
                ],
                default="BY_1",
                max_length=20,
            ),
        ),
    ]
