# Generated by Django 3.2.7 on 2021-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0004_karmaboard_table_add_value_step_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="karmaboard",
            name="sort_index",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
