# Generated by Django 3.2.7 on 2021-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0006_karmaboard_table_populate_sort_index_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="karmaboard",
            name="sort_index",
            field=models.FloatField(blank=True),
        ),
    ]
