# Generated by Django 3.2.7 on 2021-09-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0007_karmaboard_table_make_sort_index_field_non_nullable"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="karmaboard",
            name="unique_karmaboard_slug_per_owner",
        ),
        migrations.RemoveField(
            model_name="karmaboard",
            name="slug",
        ),
    ]
