# Generated by Django 3.2.7 on 2021-09-07 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0008_karmaboard_table_remove_slug_field_and_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="karma",
            name="duration_in_m",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1440)]
            ),
        ),
    ]
