# Generated by Django 3.2.7 on 2021-09-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0009_karma_table_add_duration_in_m_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnsplashPhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("regular_url", models.URLField(max_length=500)),
                ("small_url", models.URLField(max_length=500)),
                ("author_name", models.CharField(max_length=100)),
                ("author_url", models.URLField()),
            ],
            options={
                "verbose_name": "Unsplash Photo",
                "verbose_name_plural": "Unsplash Photos",
            },
        ),
    ]
