# Generated by Django 3.2.7 on 2021-09-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0010_unsplash_photo_table_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="karmaboard",
            name="unsplash_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="karmaboards",
                to="karmaspace.unsplashphoto",
            ),
        ),
    ]
