# Generated by Django 3.2.8 on 2021-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0015_karma_table_alter_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="karma",
            name="completed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="karma",
            name="is_task",
            field=models.BooleanField(default=False),
        ),
    ]
