# Generated by Django 3.2.8 on 2021-10-24 17:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("karmaspace", "0017_karma_table_add_field_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="KarmaBoardUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user_role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("MEMBER", "Member")], max_length=20
                    ),
                ),
                ("sort_index", models.FloatField(blank=True)),
                (
                    "karmaboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="karmaspace.karmaboard"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Karmaboard User",
                "verbose_name_plural": "Karmaboards Users",
            },
        ),
        migrations.AddConstraint(
            model_name="karmaboarduser",
            constraint=models.UniqueConstraint(
                fields=("karmaboard", "user"), name="unique_karmaboard_user_combination"
            ),
        ),
    ]
