# Generated by Django 3.2.7 on 2021-10-24 21:41

from django.db import migrations


def populate_karmaboard_user_table(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    KarmaBoard = apps.get_model("karmaspace", "KarmaBoard")
    KarmaBoardUser = apps.get_model("karmaspace", "KarmaBoardUser")

    for karmaboard in KarmaBoard.objects.using(db_alias).all():
        KarmaBoardUser.objects.using(db_alias).update_or_create(
            karmaboard=karmaboard,
            user=karmaboard.owner,
            defaults={
                "user_role": "OWNER",
                "sort_index": karmaboard.sort_index,
            },
        )


class Migration(migrations.Migration):

    dependencies = [("karmaspace", "0018_karmaboard_user_table_create")]

    operations = [
        migrations.RunPython(
            code=populate_karmaboard_user_table,
            reverse_code=migrations.RunPython.noop,
        )
    ]
