# Generated by Django 3.2.8 on 2021-10-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0019_karmaboard_user_table_populate"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="karmaboard",
            name="unique_karmaboard_name_per_owner",
        ),
        migrations.RemoveField(
            model_name="karmaboard",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="karmaboard",
            name="sort_index",
        ),
    ]
