# Generated by Django 3.2.8 on 2021-10-25 15:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karmaspace", "0020_karmaboard_table_integrate_with_karmaboard_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="KarmaBoardInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("secret", models.CharField(max_length=50)),
                (
                    "karmaboard",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karmaspace.karmaboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "KarmaBoard Invitation",
                "verbose_name_plural": "KarmaBoards Invitations",
            },
        ),
    ]
