# Generated by Django 3.2.7 on 2021-10-24 21:41

from django.db import migrations

from src.core.utils import create_random_string


def populate_karmaboard_invitation_table(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    KarmaBoard = apps.get_model("karmaspace", "KarmaBoard")
    KarmaBoardInvitation = apps.get_model("karmaspace", "KarmaBoardInvitation")

    for karmaboard in KarmaBoard.objects.using(db_alias).all():
        if not KarmaBoardInvitation.objects.using(db_alias).filter(karmaboard=karmaboard).exists():
            KarmaBoardInvitation.objects.using(db_alias).create(
                karmaboard=karmaboard,
                secret=create_random_string(chars_num=30),
            )


class Migration(migrations.Migration):

    dependencies = [("karmaspace", "0021_karmaboard_invitation_table_create")]

    operations = [
        migrations.RunPython(
            code=populate_karmaboard_invitation_table,
            reverse_code=migrations.RunPython.noop,
        )
    ]
