name: Recompile Python packages

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - requirements/abstract/**
    types: [ opened, synchronize ]

jobs:
  recompile_packages:
    name: Recompile packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download tusk
        run: curl -sL https://git.io/tusk | sudo bash -s -- -b /usr/local/bin latest

      - name: Update locked requirements
        run: tusk dependencies:compile

      - name: Add commit with updated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Recompile packages"
          git push
