# Generated by Django 3.2.7 on 2021-09-27 07:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("marker", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROGRESS", "In Progress"), ("DONE", "Done")], max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("name", "marker"), name="unique_job_name_and_marker_combination"
            ),
        ),
    ]
